### ISSUE TITLE
Tentei usar no ubuntu minimal não foi

### ISSUE THREAD

**Issue by acreditar** [i386angel/kali-my-linux#1]
Bom, fiz a instalação usando o comando git clone isso executei e ele nao adicionava o repo... selecionava 1 e simplesmente nao retornava nada

**Comment by marcopandolfo** [comment]
Estou tendo o mesmo problema

**Comment by ahnert37** [comment]
Teria como você mandar o caminho que se encontra os repositórios? Talvez ela esteja errando o caminho. Você tentou rodar o **sudo apt-get update**?

**Comment by ahnert37** [comment]
Já estou ciente do erro, outros usuários reportaram. Só está acontecendo no Ubuntu, medidas serão tomadas. 

Obrigado por abrir Issue.
